### ISSUE TITLE
Directory "import" not being created

### ISSUE THREAD

**Issue by dune73** [digitalwave/msc_pyparser#1]
Under examples, you note:

"Note, that the destination directory import will created."

I get

```
$> ./crs_write.py export import
Unknown dest path!

```

**Comment by airween** [comment]
Thanks @dune73 for the report.

I'ld like to avoid that the program does anything what user doesn't want, therefore I kept the code as is, but modified the [README](https://github.com/digitalwave/msc_pyparser#examples) in commit https://github.com/digitalwave/msc_pyparser/commit/ad22efdb20eb4b1241715912647a1766112629a9.

I think it's more compatible with the `crs_read.py`, and you can control always your inputs and outputs. If it's uncomfortable, just let me know, otherwise you can close this issue :).

Thanks again.

**Comment by dune73** [comment]
Perfect. I agree changing teh README is the right solution here.

I am trying to get the examples working for me now. It is not so obvious how to call the individual scripts. It must be very obvious for you, but I would benefit if the *.txt files would come with an example call.
